/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleBase: typeof import('./src/components/ArticleBase.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    ProjectTemp: typeof import('./src/components/ProjectTemp.vue')['default']
    StepStudy: typeof import('./src/components/StepStudy.vue')['default']
  }
}
